name: Run UI unit tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js 22.x (LTS)
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - name: Install dependencies
      run: npm install
    - name: Run UI unit tests
      run: npm run test-run
